### ISSUE TITLE
Pedir cartas

### ISSUE THREAD

**Issue by Haterium** [linkspreed/General_Linkspreed#794]
Pedir cartas
https://vik-game.moonactive.net/external/fbshare/askforcard_cybercowboys_7?locale=es.  🤗❤️😊👍

**Comment by Haterium** [comment]
Por favor

**Comment by linkspreed** [comment]
Hi Haterium,

how can we help you?
Do you need help with on of Linkspreed's tools?

Greetings,
Marc Herdina from Linkspreed
