### ISSUE TITLE
Space Shooter lo invita a instalar

### ISSUE THREAD

**Issue by Haterium** [linkspreed/General_Linkspreed#901]
Me gusta mucho este magnífico juego.
Pura sangre y adrenalina.  Palabra de adiccito. El que lo quiera que se lo descargué y el qué no lo deje por favor.
¡Instalar ahora! https://spaceshooter.onelink.me/tXiR/9ab149a7?pid=spaceshooter_referral&c=share_box_mainhome&af_sub5=634c5d9c39b51304d6417158

**Comment by linkspreed** [comment]
Hi Haterium,

how can we help you?
Do you need help with on of Linkspreed's tools?

Greetings,
Marc Herdina from Linkspreed
