### ISSUE TITLE
Buen juego 

### ISSUE THREAD

**Issue by Haterium** [linkspreed/General_Linkspreed#947]
https://mhome.yottagames.com/home/link/invite_tgm?&lang=es&game_id=127&deep_link_value=%7B%22lang%22%3A%22es%22%2C%22player%5Fid%22%3A%221031282972%22%7D

**Comment by linkspreed** [comment]
Hi Haterium,

how can we help you?
Do you need help with on of Linkspreed's tools?

Greetings,
Marc Herdina from Linkspreed
